[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "crypto-trade-backend"
version = "0.1.0"
edition = "2021"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.111",
    "uvicorn[standard]>=0.30",
    "pydantic>=2.8",
    "sqlalchemy>=2.0",
    "apscheduler>=3.10"
]
[tool.black]
line-length = 88
include = '\\.pyi?$'
exclude = '''(
    /\..*|/build/*|/dist/*
)'''
[tool.isort]
profile = "black"
